spring:
  datasource:
    #url: jdbc:h2:tcp://localhost/~/jpashop
    url: jpashop.ckhyvby1zevs.ap-northeast-2.rds.amazonaws.com
    username: woply
    password: jed344212
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.type : trace
